#
# Copyright (C) 2016 openwisp.org
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=OpenWISP Theme (derived from Bootstrap theme)
LUCI_DEPENDS:=+luci-theme-bootstrap

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
